disabled_rules:
    - trailing_whitespace
    - redundant_string_enum_value

opt_in_rules:
    - array_init
    - closure_spacing
    - contains_over_first_not_nil
    - convenience_type
    - discouraged_optional_boolean
    - empty_count
    - empty_string
    - empty_xctest_method
    - explicit_enum_raw_value
    - explicit_init
    - fallthrough
    - fatal_error_message
    - first_where
    - force_unwrapping
    - let_var_whitespace
    - modifier_order
    - overridden_super_call
    - prefixed_toplevel_constant
    - private_action
    - private_outlet
    - prohibited_super_call
    - redundant_nil_coalescing
    - redundant_optional_initialization
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - trailing_closure
    - unneeded_parentheses_in_closure_argument
    - yoda_condition

excluded: #paths to ignore during linting. Takes precedence over 'included'.
    - Carthage
    - SnapKit
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length: 140
file_length:
  warning: 500
  error: 1200

custom_rules:
    comments_space: # From https://github.com/brandenr/swiftlintconfig
        name: "Space After Comment"
        regex: "(^ *//\\w+)"
        message: "There should be a space after //"
        severity: warning
